metadata.format.version = "1.1"

[versions]

# Compile only
velocity = "3.2.0-SNAPSHOT"
libby = "43d25ade72"
bstats = "3.0.0"
configurate = "4.1.2"
miniplaceholders = "1.3.1"

# Plugins
blossom = "1.3.1"
shadow = "7.1.2"
runvelocity = "2.0.1"

# Test versions
slf4j = "2.0.6"
assertj = "3.24.2"

# Required by Configurate 4
geantyref = "1.3.13"

# Velocity dependencies included in classpath but not in API
caffeine = "3.1.2"

[libraries]

# Compile Only Dependencies
velocity = { group = "com.velocitypowered", name = "velocity-api", version.ref = "velocity" }
bstats = { module = "org.bstats:bstats-velocity", version.ref = "bstats" }
configurate = { module = "org.spongepowered:configurate-hocon", version.ref = "configurate" }
miniplaceholders = { group = "com.github.4drian3d", name = "MiniPlaceholders", version.ref = "miniplaceholders" }

# Included Dependencies
libby = { group = "com.github.AlessioDP.libby", name = "libby-velocity", version.ref = "libby" }

# Test Dependencies
slf4j = { module = "org.slf4j:slf4j-api", version.ref = "slf4j" }
assetrj = { module = "org.assertj:assertj-core", version.ref = "assertj" }

# Velocity dependencies included in classpath but not in API
caffeine = { module = "com.github.ben-manes.caffeine:caffeine", version.ref = "caffeine" }

[plugins]

blossom = { id = "net.kyori.blossom", version.ref = "blossom" }
shadow = { id = "com.github.johnrengelman.shadow", version.ref = "shadow" }
runvelocity = { id = "xyz.jpenilla.run-velocity", version.ref = "runvelocity" }